/***********************************************************************/
/*                                                                     */
/*  FILE        :intprg.c                                              */
/*  DATE        :Wed, Sep 12, 2018                                     */
/*  DESCRIPTION :Interrupt Program                                     */
/*  CPU TYPE    :SH7286                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : SH-2A/SH7286
*
* File Name  : intprg.c
*
* Abstract   : Interrupt Program.
*
* History    : 1.00  (2008-12-16)  [Hardware Manual Revision : 1.00]
*
* Copyright(c) 2008 Renesas Technology Corp.
*               And Renesas Solutions Corp.,All Rights Reserved. 
*
*********************************************************************/

#include <machine.h>
#include "vect.h"
#pragma section IntPRG

// 4 Illegal code
void INT_Illegal_code(void){/* sleep(); */}
// 5 Reserved

// 6 Illegal slot
void INT_Illegal_slot(void){/* sleep(); */}
// 7 Reserved

// 8 Reserved

// 9 CPU Address error
void INT_CPU_Address(void){/* sleep(); */}
// 10 DMAC Address error
void INT_DMAC_Address(void){/* sleep(); */}
// 11 NMI
void INT_NMI(void){/* sleep(); */}
// 12 User breakpoint trap
void INT_User_Break(void){/* sleep(); */}
// 13 Reserved

// 14 H-UDI
void INT_HUDI(void){/* sleep(); */}
// 15 Register bank over
void INT_Bank_Overflow(void){/* sleep(); */}
// 16 Register bank under
void INT_Bank_Underflow(void){/* sleep(); */}
// 17 ZERO_DIV
void INT_Divide_by_Zero(void){/* sleep(); */}
// 18 OVER_DIV
void INT_Divide_Overflow(void){/* sleep(); */}
// 19 Reserved

// 20 Reserved

// 21 Reserved

// 22 Reserved

// 23 Reserved

// 24 Reserved

// 25 Reserved

// 26 Reserved

// 27 Reserved

// 28 Reserved

// 29 Reserved

// 30 Reserved

// 31 Reserved

// 32 TRAPA (User Vecter)
void INT_TRAPA32(void){/* sleep(); */}
// 33 TRAPA (User Vecter)
void INT_TRAPA33(void){/* sleep(); */}
// 34 TRAPA (User Vecter)
void INT_TRAPA34(void){/* sleep(); */}
// 35 TRAPA (User Vecter)
void INT_TRAPA35(void){/* sleep(); */}
// 36 TRAPA (User Vecter)
void INT_TRAPA36(void){/* sleep(); */}
// 37 TRAPA (User Vecter)
void INT_TRAPA37(void){/* sleep(); */}
// 38 TRAPA (User Vecter)
void INT_TRAPA38(void){/* sleep(); */}
// 39 TRAPA (User Vecter)
void INT_TRAPA39(void){/* sleep(); */}
// 40 TRAPA (User Vecter)
void INT_TRAPA40(void){/* sleep(); */}
// 41 TRAPA (User Vecter)
void INT_TRAPA41(void){/* sleep(); */}
// 42 TRAPA (User Vecter)
void INT_TRAPA42(void){/* sleep(); */}
// 43 TRAPA (User Vecter)
void INT_TRAPA43(void){/* sleep(); */}
// 44 TRAPA (User Vecter)
void INT_TRAPA44(void){/* sleep(); */}
// 45 TRAPA (User Vecter)
void INT_TRAPA45(void){/* sleep(); */}
// 46 TRAPA (User Vecter)
void INT_TRAPA46(void){/* sleep(); */}
// 47 TRAPA (User Vecter)
void INT_TRAPA47(void){/* sleep(); */}
// 48 TRAPA (User Vecter)
void INT_TRAPA48(void){/* sleep(); */}
// 49 TRAPA (User Vecter)
void INT_TRAPA49(void){/* sleep(); */}
// 50 TRAPA (User Vecter)
void INT_TRAPA50(void){/* sleep(); */}
// 51 TRAPA (User Vecter)
void INT_TRAPA51(void){/* sleep(); */}
// 52 TRAPA (User Vecter)
void INT_TRAPA52(void){/* sleep(); */}
// 53 TRAPA (User Vecter)
void INT_TRAPA53(void){/* sleep(); */}
// 54 TRAPA (User Vecter)
void INT_TRAPA54(void){/* sleep(); */}
// 55 TRAPA (User Vecter)
void INT_TRAPA55(void){/* sleep(); */}
// 56 TRAPA (User Vecter)
void INT_TRAPA56(void){/* sleep(); */}
// 57 TRAPA (User Vecter)
void INT_TRAPA57(void){/* sleep(); */}
// 58 TRAPA (User Vecter)
void INT_TRAPA58(void){/* sleep(); */}
// 59 TRAPA (User Vecter)
void INT_TRAPA59(void){/* sleep(); */}
// 60 TRAPA (User Vecter)
void INT_TRAPA60(void){/* sleep(); */}
// 61 TRAPA (User Vecter)
void INT_TRAPA61(void){/* sleep(); */}
// 62 TRAPA (User Vecter)
void INT_TRAPA62(void){/* sleep(); */}
// 63 TRAPA (User Vecter)
void INT_TRAPA63(void){/* sleep(); */}
// 64 Interrupt IRQ0
void INT_IRQ0(void){/* sleep(); */}
// 65 Interrupt IRQ1
void INT_IRQ1(void){/* sleep(); */}
// 66 Interrupt IRQ2
void INT_IRQ2(void){/* sleep(); */}
// 67 Interrupt IRQ3
void INT_IRQ3(void){/* sleep(); */}
// 68 Interrupt IRQ4
void INT_IRQ4(void){/* sleep(); */}
// 69 Interrupt IRQ5
void INT_IRQ5(void){/* sleep(); */}
// 70 Interrupt IRQ6
void INT_IRQ6(void){/* sleep(); */}
// 71 Interrupt IRQ7
void INT_IRQ7(void){/* sleep(); */}
// 72 Reserved

// 73 Reserved

// 74 Reserved

// 75 Reserved

// 76 Reserved

// 77 Reserved

// 78 Reserved

// 79 Reserved

// 80 Reserved

// 81 Reserved

// 82 Reserved

// 83 Reserved

// 84 Reserved

// 85 Reserved

// 86 Reserved

// 87 Reserved

// 88 Reserved

// 89 Reserved

// 90 Reserved

// 91 Reserved

// 92  ADC ADI0
void INT_ADC_ADI0(void){/* sleep(); */}
// 93 Reserved

// 94 Reserved

// 95 Reserved

// 96 ADC ADI1
void INT_ADC_ADI1(void){/* sleep(); */}
// 97 Reserved

// 98 Reserved

// 99 Reserved

// 100 ADC ADI2
void INT_ADC_ADI2(void){/* sleep(); */}
// 101 Reserved

// 102 Reserved

// 103 Reserved

// 104 RCAN ERS_0
void INT_RCAN_ERS0(void){/* sleep(); */}
// 105 RCAN OVR_0
void INT_RCAN_OVR0(void){/* sleep(); */}
// 106 RCAN RM0_0/RM1_0
void INT_RCAN_RM0(void){/* sleep(); */}
// 107 RCAN SLE_0
void INT_RCAN_SLE0(void){/* sleep(); */}
// 108 DMAC0 DEI0
void INT_DMAC0_DEI0(void){/* sleep(); */}
// 109 DMAC0 HEI0
void INT_DMAC0_HEI0(void){/* sleep(); */}
// 110 Reserved

// 111 Reserved

// 112 DMAC1 DEI1
void INT_DMAC1_DEI1(void){/* sleep(); */}
// 113 DMAC1 HEI1
void INT_DMAC1_HEI1(void){/* sleep(); */}
// 114 Reserved

// 115 Reserved

// 116 DMAC2 DEI2
void INT_DMAC2_DEI2(void){/* sleep(); */}
// 117 DMAC2 HEI2
void INT_DMAC2_HEI2(void){/* sleep(); */}
// 118 Reserved

// 119 Reserved

// 120 DMAC3 DEI3
void INT_DMAC3_DEI3(void){/* sleep(); */}
// 121 DMAC3 HEI3
void INT_DMAC3_HEI3(void){/* sleep(); */}
// 122 Reserved

// 123 Reserved

// 124 DMAC4 DEI4
void INT_DMAC4_DEI4(void){/* sleep(); */}
// 125 DMAC4 HEI4
void INT_DMAC4_HEI4(void){/* sleep(); */}
// 126 Reserved

// 127 Reserved

// 128 DMAC5 DEI5
void INT_DMAC5_DEI5(void){/* sleep(); */}
// 129 DMAC5 HEI5
void INT_DMAC5_HEI5(void){/* sleep(); */}
// 130 Reserved

// 131 Reserved

// 132 DMAC6 DEI6
void INT_DMAC6_DEI6(void){/* sleep(); */}
// 133 DMAC6 HEI6
void INT_DMAC6_HEI6(void){/* sleep(); */}
// 134 Reserved

// 135 Reserved

// 136 DMAC7 DEI7
void INT_DMAC7_DEI7(void){/* sleep(); */}
// 137 DMAC7 HEI7
void INT_DMAC7_HEI7(void){/* sleep(); */}
// 138 Reserved

// 139 Reserved

// 140 CMT CMI0
void INT_CMT_CMI0(void){/* sleep(); */}
// 141 Reserved

// 142 Reserved

// 143 Reserved

// 144 CMT CMI1
void INT_CMT_CMI1(void){/* sleep(); */}
// 145 Reserved

// 146 Reserved

// 147 Reserved

// 148 BSC CMI
void INT_BSC_CMI(void){/* sleep(); */}
// 149 Reserved

// 150 Reserved

// 151 Reserved

// 152 WDT ITI
void INT_WDT_ITI(void){/* sleep(); */}
// 153 Reserved

// 154 USB EP1_FULL_END
void INT_USB_EP1_FULL_END(void){/* sleep(); */}
// 155 USB EP2_EMPTY_END
void INT_USB_EP2_EMPTY_END(void){/* sleep(); */}
// 156 MTU2 MTU0 TGIA0
void INT_MTU2_MTU0_TGIA0(void){/* sleep(); */}
// 157 MTU2 MTU0 TGIB0
void INT_MTU2_MTU0_TGIB0(void){/* sleep(); */}
// 158 MTU2 MTU0 TGIC0
void INT_MTU2_MTU0_TGIC0(void){/* sleep(); */}
// 159 MTU2 MTU0 TGID0
void INT_MTU2_MTU0_TGID0(void){/* sleep(); */}
// 160 MTU2 MTU0 TCIV0
void INT_MTU2_MTU0_TCIV0(void){/* sleep(); */}
// 161 MTU2 MTU0 TGIE0
void INT_MTU2_MTU0_TGIE0(void){/* sleep(); */}
// 162 MTU2 MTU0 TGIF0
void INT_MTU2_MTU0_TGIF0(void){/* sleep(); */}
// 163 Reserved

// 164 MTU2 MTU1 TGIA1
void INT_MTU2_MTU1_TGIA1(void){/* sleep(); */}
// 165 MTU2 MTU1 TGIB1
void INT_MTU2_MTU1_TGIB1(void){/* sleep(); */}
// 166 Reserved 

// 167 Reserved

// 168 MTU2 MTU1 TCIV1
void INT_MTU2_MTU1_TCIV1(void){/* sleep(); */}
// 169 MTU2 MTU1 TCIU1
void INT_MTU2_MTU1_TCIU1(void){/* sleep(); */}
// 170 Reserved 

// 171 Reserved

// 172 MTU2 MTU2 TGIA2
void INT_MTU2_MTU2_TGIA2(void){/* sleep(); */}
// 173 MTU2 MTU2 TGIB2
void INT_MTU2_MTU2_TGIB2(void){/* sleep(); */}
// 174 Reserved 

// 175 Reserved

// 176 MTU2 MTU2 TCIV2
void INT_MTU2_MTU2_TCIV2(void){/* sleep(); */}
// 177 MTU2 MTU2 TCIU2
void INT_MTU2_MTU2_TCIU2(void){/* sleep(); */}
// 178 Reserved 

// 179 Reserved

// 180 MTU2 MTU3 TGIA3
void INT_MTU2_MTU3_TGIA3(void){/* sleep(); */}
// 181 MTU2 MTU3 TGIB3
void INT_MTU2_MTU3_TGIB3(void){/* sleep(); */}
// 182 MTU2 MTU3 TGIC3
void INT_MTU2_MTU3_TGIC3(void){/* sleep(); */}
// 183 MTU2 MTU3 TGID3
void INT_MTU2_MTU3_TGID3(void){/* sleep(); */}
// 184 MTU2 MTU3 TCIV3
void INT_MTU2_MTU3_TCIV3(void){/* sleep(); */}
// 185 Reserved 

// 186 Reserved

// 187 Reserved 

// 188 MTU2 MTU4 TGIA4
void INT_MTU2_MTU4_TGIA4(void){/* sleep(); */}
// 189 MTU2 MTU4 TGIB4
void INT_MTU2_MTU4_TGIB4(void){/* sleep(); */}
// 190 MTU2 MTU4 TGIC4
void INT_MTU2_MTU4_TGIC4(void){/* sleep(); */}
// 191 MTU2 MTU4 TGID4
void INT_MTU2_MTU4_TGID4(void){/* sleep(); */}
// 192 MTU2 MTU4 TCIV4
void INT_MTU2_MTU4_TCIV4(void){/* sleep(); */}
// 193 Reserved 

// 194 Reserved

// 195 Reserved 

// 196 MTU2 MTU5 TGIU5
void INT_MTU2_MTU5_TGIU5(void){/* sleep(); */}
// 197 MTU2 MTU5 TGIV5
void INT_MTU2_MTU5_TGIV5(void){/* sleep(); */}
// 198 MTU2 MTU5 TGIW5
void INT_MTU2_MTU5_TGIW5(void){/* sleep(); */}
// 199 Reserved 

// 200 POE2 OEI1
void INT_POE2_OEI1(void){/* sleep(); */}
// 201 POE2 OEI2 
void INT_POE2_OEI2(void){/* sleep(); */}
// 202 Reserved 

// 203 Reserved

// 204 MTU2S MTU3S TGIA3
void INT_MTU2S_MTU3S_TGIA3(void){/* sleep(); */}
// 205 MTU2S MTU3S TGIB3
void INT_MTU2S_MTU3S_TGIB3(void){/* sleep(); */}
// 206 MTU2S MTU3S TGIC3
void INT_MTU2S_MTU3S_TGIC3(void){/* sleep(); */}
// 207 MTU2S MTU3S TGID3 
void INT_MTU2S_MTU3S_TGID3(void){/* sleep(); */}
// 208 MTU2S MTU3S TCIV3
void INT_MTU2S_MTU3S_TCIV3(void){/* sleep(); */}
// 209 Reserved 

// 210 Reserved 

// 211 Reserved

// 212 MTU2S MTU4S TGIA4
void INT_MTU2S_MTU4S_TGIA4(void){/* sleep(); */}
// 213 MTU2S MTU4S TGIB4
void INT_MTU2S_MTU4S_TGIB4(void){/* sleep(); */}
// 214 MTU2S MTU4S TGIC4
void INT_MTU2S_MTU4S_TGIC4(void){/* sleep(); */}
// 215 MTU2S MTU4S TGID4
void INT_MTU2S_MTU4S_TGID4(void){/* sleep(); */}
// 216 MTU2S MTU4S TCIV4
void INT_MTU2S_MTU4S_TCIV4(void){/* sleep(); */}
// 217 Reserved 

// 218 Reserved

// 219 Reserved 

// 220 MTU2S MTU5S TGIU5
void INT_MTU2S_MTU5S_TGIU5(void){/* sleep(); */}
// 221 MTU2S MTU5S TGIV5
void INT_MTU2S_MTU5S_TGIV5(void){/* sleep(); */}
// 222 MTU2S MTU5S TGIW5
void INT_MTU2S_MTU5S_TGIW5(void){/* sleep(); */}
// 223 Reserved

// 224 POE2 OEI3
void INT_POE2_OEI3(void){/* sleep(); */}
// 225 Reserved

// 226 USB USI0
void INT_USB_USI0(void){/* sleep(); */}
// 227 USB USI1
void INT_USB_USI1(void){/* sleep(); */}
// 228 IIC3 STPI
void INT_IIC3_STPI(void){/* sleep(); */}
// 229 IIC3 NAKI
void INT_IIC3_NAKI(void){/* sleep(); */}
// 230 IIC3 RXI
void INT_IIC3_RXI(void){/* sleep(); */}
// 231 IIC3 TXI
void INT_IIC3_TXI(void){/* sleep(); */}
// 232 IIC3 TEI
void INT_IIC3_TEI(void){/* sleep(); */}
// 233 SSU SSERI
void INT_SSU_SSERI(void){/* sleep(); */}
// 234 SSU SSRXI
void INT_SSU_SSRXI(void){/* sleep(); */}
// 235 SSU SSTXI
void INT_SSU_SSTXI(void){/* sleep(); */}
// 236 SCI SCI4 ERI4
void INT_SCI_SCI4_ERI4(void){/* sleep(); */}
// 237 SCI SCI4 RXI4
void INT_SCI_SCI4_RXI4(void){/* sleep(); */}
// 238 SCI SCI4 TXI4
void INT_SCI_SCI4_TXI4(void){/* sleep(); */}
// 239 SCI SCI4 TEI4
void INT_SCI_SCI4_TEI4(void){/* sleep(); */}
// 240 SCI SCI0 ERI0
void INT_SCI_SCI0_ERI0(void){/* sleep(); */}
// 241 SCI SCI0 RXI0
void INT_SCI_SCI0_RXI0(void){/* sleep(); */}
// 242 SCI SCI0 TXI0
void INT_SCI_SCI0_TXI0(void){/* sleep(); */}
// 243 SCI SCI0 TEI0
void INT_SCI_SCI0_TEI0(void){/* sleep(); */}
// 244 SCI SCI1 ERI1
void INT_SCI_SCI1_ERI1(void){/* sleep(); */}
// 245 SCI SCI1 RXI1
void INT_SCI_SCI1_RXI1(void){/* sleep(); */}
// 246 SCI SCI1 TXI1
void INT_SCI_SCI1_TXI1(void){/* sleep(); */}
// 247 SCI SCI1 TEI1
void INT_SCI_SCI1_TEI1(void){/* sleep(); */}
// 248 SCI SCI2 ERI2
void INT_SCI_SCI2_ERI2(void){/* sleep(); */}
// 249 SCI SCI2 RXI2
void INT_SCI_SCI2_RXI2(void){/* sleep(); */}
// 250 SCI SCI2 TXI2
void INT_SCI_SCI2_TXI2(void){/* sleep(); */}
// 251 SCI SCI2 TEI2
void INT_SCI_SCI2_TEI2(void){/* sleep(); */}
// 252 SCIF SCIF3 BRI3
void INT_SCIF_SCIF3_BRI3(void){/* sleep(); */}
// 253 SCIF SCIF3 ERI3
void INT_SCIF_SCIF3_ERI3(void){/* sleep(); */}
// 254 SCIF SCIF3 RXI3
void INT_SCIF_SCIF3_RXI3(void){/* sleep(); */}
// 255 SCIF SCIF3 TXI3
void INT_SCIF_SCIF3_TXI3(void){/* sleep(); */}
// 256 Reserved

// 257 Reserved

// 258 Reserved

// 259 Reserved

// 260 Reserved

// 261 Reserved

// 262 Reserved

// 263 Reserved

// 264 Reserved

// 265 Reserved

// 266 Reserved

// 267 Reserved

// 268 Reserved

// 269 Reserved

// 270 Reserved

// 271 Reserved

// 272 Reserved

// 273 Reserved

// 274 Reserved

// 275 Reserved

// 276 Reserved

// 277 Reserved

// 278 Reserved

// 279 Reserved

// 280 Reserved

// 281 Reserved

// 282 Reserved

// 283 Reserved

// 284 Reserved

// 285 Reserved

// 286 Reserved

// 287 Reserved

// 288 Reserved

// 289 Reserved

// 290 Reserved

// 291 Reserved

// 292 Reserved

// 293 Reserved

// 294 Reserved

// 295 Reserved

// 296 Reserved

// 297 Reserved

// 298 Reserved

// 299 Reserved

// 300 Reserved

// 301 Reserved

// 302 Reserved

// 303 Reserved

// 304 Reserved

// 305 Reserved

// 306 Reserved

// 307 Reserved

// 308 Reserved

// 309 Reserved

// 310 Reserved

// 311 Reserved

// 312 Reserved

// 313 Reserved

// 314 Reserved

// 315 Reserved

// 316 Reserved

// 317 Reserved

// 318 Reserved

// 319 Reserved

// 320 Reserved

// 321 Reserved

// 322 Reserved

// 323 Reserved

// 324 Reserved

// 325 Reserved

// 326 Reserved

// 327 Reserved

// 328 Reserved

// 329 Reserved

// 330 Reserved

// 331 Reserved

// 332 Reserved

// 333 Reserved

// 334 Reserved

// 335 Reserved

// 336 Reserved

// 337 Reserved

// 338 Reserved

// 339 Reserved

// 340 Reserved

// 341 Reserved

// 342 Reserved

// 343 Reserved

// 344 Reserved

// 345 Reserved

// 346 Reserved

// 347 Reserved

// 348 Reserved

// 349 Reserved

// 350 Reserved

// 351 Reserved

// 352 Reserved

// 353 Reserved

// 354 Reserved

// 355 Reserved

// 356 Reserved

// 357 Reserved

// 358 Reserved

// 359 Reserved

// 360 Reserved

// 361 Reserved

// 362 Reserved

// 363 Reserved

// 364 Reserved

// 365 Reserved

// 366 Reserved

// 367 Reserved

// 368 Reserved

// 369 Reserved

// 370 Reserved

// 371 Reserved

// 372 Reserved

// 373 Reserved

// 374 Reserved

// 375 Reserved

// 376 Reserved

// 377 Reserved

// 378 Reserved

// 379 Reserved

// 380 Reserved

// 381 Reserved

// 382 Reserved

// 383 Reserved

// 384 Reserved

// 385 Reserved

// 386 Reserved

// 387 Reserved

// 388 Reserved

// 389 Reserved

// 390 Reserved

// 391 Reserved

// 392 Reserved

// 393 Reserved

// 394 Reserved

// 395 Reserved

// 396 Reserved

// 397 Reserved

// 398 Reserved

// 399 Reserved

// 400 Reserved

// 401 Reserved

// 402 Reserved

// 403 Reserved

// 404 Reserved

// 405 Reserved

// 406 Reserved

// 407 Reserved

// 408 Reserved

// 409 Reserved

// 410 Reserved

// 411 Reserved

// 412 Reserved

// 413 Reserved

// 414 Reserved

// 415 Reserved

// 416 Reserved

// 417 Reserved

// 418 Reserved

// 419 Reserved

// 420 Reserved

// 421 Reserved

// 422 Reserved

// 423 Reserved

// 424 Reserved

// 425 Reserved

// 426 Reserved

// 427 Reserved

// 428 Reserved

// 429 Reserved

// 430 Reserved

// 431 Reserved

// 432 Reserved

// 433 Reserved

// 434 Reserved

// 435 Reserved

// 436 Reserved

// 437 Reserved

// 438 Reserved

// 439 Reserved

// 440 Reserved

// 441 Reserved

// 442 Reserved

// 443 Reserved

// 444 Reserved

// 445 Reserved

// 446 Reserved

// 447 Reserved

// 448 Reserved

// 449 Reserved

// 450 Reserved

// 451 Reserved

// 452 Reserved

// 453 Reserved

// 454 Reserved

// 455 Reserved

// 456 Reserved

// 457 Reserved

// 458 Reserved

// 459 Reserved

// 460 Reserved

// 461 Reserved

// 462 Reserved

// 463 Reserved

// 464 Reserved

// 465 Reserved

// 466 Reserved

// 467 Reserved

// 468 Reserved

// 469 Reserved

// 470 Reserved

// 471 Reserved

// 472 Reserved

// 473 Reserved

// 474 Reserved

// 475 Reserved

// 476 Reserved

// 477 Reserved

// 478 Reserved

// 479 Reserved

// 480 Reserved

// 481 Reserved

// 482 Reserved

// 483 Reserved

// 484 Reserved

// 485 Reserved

// 486 Reserved

// 487 Reserved

// 488 Reserved

// 489 Reserved

// 490 Reserved

// 491 Reserved

// 492 Reserved

// 493 Reserved

// 494 Reserved

// 495 Reserved

// 496 Reserved

// 497 Reserved

// 498 Reserved

// 499 Reserved

// 500 Reserved

// 501 Reserved

// 502 Reserved

// 503 Reserved

// 504 Reserved

// 505 Reserved

// 506 Reserved

// 507 Reserved

// 508 Reserved

// 509 Reserved

// 510 Reserved

// 511 Reserved

// Dummy
void Dummy(void){/* sleep(); */}
