/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Wed, Sep 12, 2018                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :SH7286                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 20
