/***********************************************************************/
/*                                                                     */
/*  FILE        :vect.h                                                */
/*  DATE        :Wed, Sep 12, 2018                                     */
/*  DESCRIPTION :Definition of Vector                                  */
/*  CPU TYPE    :SH7286                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : SH-2A/SH7286
*
* File Name  : vect.h
*
* Abstract   : Definition of Vector.
*
* History    : 1.00  (2008-12-16)  [Hardware Manual Revision : 1.00]
*
* Copyright(c) 2008 Renesas Technology Corp.
*               And Renesas Solutions Corp.,All Rights Reserved. 
*
*********************************************************************/

//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset PC
extern void PowerON_Reset_PC(void);

//;<<VECTOR DATA END (POWER ON RESET)>>
// 1 Power On Reset SP

//;<<VECTOR DATA START (MANUAL RESET)>>
//;2 Manual Reset PC
extern void Manual_Reset_PC(void);

//;<<VECTOR DATA END (MANUAL RESET)>>
// 3 Manual Reset SP

// 4 Illegal code
#pragma interrupt INT_Illegal_code
extern void INT_Illegal_code(void);

// 5 Reserved

// 6 Illegal slot
#pragma interrupt INT_Illegal_slot
extern void INT_Illegal_slot(void);

// 7 Reserved

// 8 Reserved

// 9 CPU Address error
#pragma interrupt INT_CPU_Address
extern void INT_CPU_Address(void);

// 10 DMAC Address error
#pragma interrupt INT_DMAC_Address
extern void INT_DMAC_Address(void);

// 11 NMI
#pragma interrupt INT_NMI
extern void INT_NMI(void);

// 12 User breakpoint trap
#pragma interrupt INT_User_Break
extern void INT_User_Break(void);

// 13 Reserved

// 14 H-UDI
#pragma interrupt INT_HUDI
extern void INT_HUDI(void);

// 15 Register bank over
#pragma interrupt INT_Bank_Overflow
extern void INT_Bank_Overflow(void);

// 16 Register bank under
#pragma interrupt INT_Bank_Underflow
extern void INT_Bank_Underflow(void);

// 17 ZERO_DIV
#pragma interrupt INT_Divide_by_Zero
extern void INT_Divide_by_Zero(void);

// 18 OVER_DIV
#pragma interrupt INT_Divide_Overflow
extern void INT_Divide_Overflow(void);

// 19 Reserved

// 20 Reserved

// 21 Reserved

// 22 Reserved

// 23 Reserved

// 24 Reserved

// 25 Reserved

// 26 Reserved

// 27 Reserved

// 28 Reserved

// 29 Reserved

// 30 Reserved

// 31 Reserved

// 32 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA32
extern void INT_TRAPA32(void);

// 33 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA33
extern void INT_TRAPA33(void);

// 34 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA34
extern void INT_TRAPA34(void);

// 35 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA35
extern void INT_TRAPA35(void);

// 36 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA36
extern void INT_TRAPA36(void);

// 37 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA37
extern void INT_TRAPA37(void);

// 38 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA38
extern void INT_TRAPA38(void);

// 39 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA39
extern void INT_TRAPA39(void);

// 40 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA40
extern void INT_TRAPA40(void);

// 41 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA41
extern void INT_TRAPA41(void);

// 42 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA42
extern void INT_TRAPA42(void);

// 43 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA43
extern void INT_TRAPA43(void);

// 44 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA44
extern void INT_TRAPA44(void);

// 45 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA45
extern void INT_TRAPA45(void);

// 46 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA46
extern void INT_TRAPA46(void);

// 47 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA47
extern void INT_TRAPA47(void);

// 48 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA48
extern void INT_TRAPA48(void);

// 49 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA49
extern void INT_TRAPA49(void);

// 50 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA50
extern void INT_TRAPA50(void);

// 51 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA51
extern void INT_TRAPA51(void);

// 52 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA52
extern void INT_TRAPA52(void);

// 53 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA53
extern void INT_TRAPA53(void);

// 54 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA54
extern void INT_TRAPA54(void);

// 55 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA55
extern void INT_TRAPA55(void);

// 56 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA56
extern void INT_TRAPA56(void);

// 57 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA57
extern void INT_TRAPA57(void);

// 58 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA58
extern void INT_TRAPA58(void);

// 59 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA59
extern void INT_TRAPA59(void);

// 60 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA60
extern void INT_TRAPA60(void);

// 61 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA61
extern void INT_TRAPA61(void);

// 62 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA62
extern void INT_TRAPA62(void);

// 63 TRAPA (User Vecter)
#pragma interrupt INT_TRAPA63
extern void INT_TRAPA63(void);

// 64 Interrupt IRQ0
#pragma interrupt INT_IRQ0
extern void INT_IRQ0(void);

// 65 Interrupt IRQ1
#pragma interrupt INT_IRQ1
extern void INT_IRQ1(void);

// 66 Interrupt IRQ2
#pragma interrupt INT_IRQ2
extern void INT_IRQ2(void);

// 67 Interrupt IRQ3
#pragma interrupt INT_IRQ3
extern void INT_IRQ3(void);

// 68 Interrupt IRQ4
#pragma interrupt INT_IRQ4
extern void INT_IRQ4(void);

// 69 Interrupt IRQ5
#pragma interrupt INT_IRQ5
extern void INT_IRQ5(void);

// 70 Interrupt IRQ6
#pragma interrupt INT_IRQ6
extern void INT_IRQ6(void);

// 71 Interrupt IRQ7
#pragma interrupt INT_IRQ7
extern void INT_IRQ7(void);

// 72 Reserved

// 73 Reserved

// 74 Reserved

// 75 Reserved

// 76 Reserved

// 77 Reserved

// 78 Reserved

// 79 Reserved

// 80 Reserved

// 81 Reserved

// 82 Reserved

// 83 Reserved

// 84 Reserved

// 85 Reserved

// 86 Reserved

// 87 Reserved

// 88 Reserved

// 89 Reserved

// 90 Reserved

// 91 Reserved

// 92  ADC ADI0
#pragma interrupt INT_ADC_ADI0
extern void INT_ADC_ADI0(void);

// 93 Reserved

// 94 Reserved

// 95 Reserved

// 96 ADC ADI1
#pragma interrupt INT_ADC_ADI1
extern void INT_ADC_ADI1(void);

// 97 Reserved

// 98 Reserved

// 99 Reserved

// 100 ADC ADI2
#pragma interrupt INT_ADC_ADI2
extern void INT_ADC_ADI2(void);

// 101 Reserved

// 102 Reserved

// 103 Reserved

// 104 RCAN ERS_0
#pragma interrupt INT_RCAN_ERS0
extern void INT_RCAN_ERS0(void);

// 105 RCAN OVR_0
#pragma interrupt INT_RCAN_OVR0
extern void INT_RCAN_OVR0(void);

// 106 RCAN RM0_0/RM1_0
#pragma interrupt INT_RCAN_RM0
extern void INT_RCAN_RM0(void);

// 107 RCAN SLE_0
#pragma interrupt INT_RCAN_SLE0
extern void INT_RCAN_SLE0(void);

// 108 DMAC0 DEI0
#pragma interrupt INT_DMAC0_DEI0
extern void INT_DMAC0_DEI0(void);

// 109 DMAC0 HEI0
#pragma interrupt INT_DMAC0_HEI0
extern void INT_DMAC0_HEI0(void);

// 110 Reserved

// 111 Reserved

// 112 DMAC1 DEI1
#pragma interrupt INT_DMAC1_DEI1
extern void INT_DMAC1_DEI1(void);

// 113 DMAC1 HEI1
#pragma interrupt INT_DMAC1_HEI1
extern void INT_DMAC1_HEI1(void);

// 114 Reserved

// 115 Reserved

// 116 DMAC2 DEI2
#pragma interrupt INT_DMAC2_DEI2
extern void INT_DMAC2_DEI2(void);

// 117 DMAC2 HEI2
#pragma interrupt INT_DMAC2_HEI2
extern void INT_DMAC2_HEI2(void);

// 118 Reserved

// 119 Reserved

// 120 DMAC3 DEI3
#pragma interrupt INT_DMAC3_DEI3
extern void INT_DMAC3_DEI3(void);

// 121 DMAC3 HEI3
#pragma interrupt INT_DMAC3_HEI3
extern void INT_DMAC3_HEI3(void);

// 122 Reserved

// 123 Reserved

// 124 DMAC4 DEI4
#pragma interrupt INT_DMAC4_DEI4
extern void INT_DMAC4_DEI4(void);

// 125 DMAC4 HEI4
#pragma interrupt INT_DMAC4_HEI4
extern void INT_DMAC4_HEI4(void);

// 126 Reserved

// 127 Reserved

// 128 DMAC5 DEI5
#pragma interrupt INT_DMAC5_DEI5
extern void INT_DMAC5_DEI5(void);

// 129 DMAC5 HEI5
#pragma interrupt INT_DMAC5_HEI5
extern void INT_DMAC5_HEI5(void);

// 130 Reserved

// 131 Reserved

// 132 DMAC6 DEI6
#pragma interrupt INT_DMAC6_DEI6
extern void INT_DMAC6_DEI6(void);

// 133 DMAC6 HEI6
#pragma interrupt INT_DMAC6_HEI6
extern void INT_DMAC6_HEI6(void);

// 134 Reserved

// 135 Reserved

// 136 DMAC7 DEI7
#pragma interrupt INT_DMAC7_DEI7
extern void INT_DMAC7_DEI7(void);

// 137 DMAC7 HEI7
#pragma interrupt INT_DMAC7_HEI7
extern void INT_DMAC7_HEI7(void);

// 138 Reserved

// 139 Reserved

// 140 CMT CMI0
#pragma interrupt INT_CMT_CMI0
extern void INT_CMT_CMI0(void);

// 141 Reserved

// 142 Reserved

// 143 Reserved

// 144 CMT CMI1
#pragma interrupt INT_CMT_CMI1
extern void INT_CMT_CMI1(void);

// 145 Reserved

// 146 Reserved

// 147 Reserved

// 148 BSC CMI
#pragma interrupt INT_BSC_CMI
extern void INT_BSC_CMI(void);

// 149 Reserved

// 150 Reserved

// 151 Reserved

// 152 WDT ITI
#pragma interrupt INT_WDT_ITI
extern void INT_WDT_ITI(void);

// 153 Reserved

// 154 USB EP1_FULL_END
#pragma interrupt INT_USB_EP1_FULL_END
extern void INT_USB_EP1_FULL_END(void);

// 155 USB EP2_EMPTY_END
#pragma interrupt INT_USB_EP2_EMPTY_END
extern void INT_USB_EP2_EMPTY_END(void);

// 156 MTU2 MTU0 TGIA0
#pragma interrupt INT_MTU2_MTU0_TGIA0
extern void INT_MTU2_MTU0_TGIA0(void);

// 157 MTU2 MTU0 TGIB0
#pragma interrupt INT_MTU2_MTU0_TGIB0
extern void INT_MTU2_MTU0_TGIB0(void);

// 158 MTU2 MTU0 TGIC0
#pragma interrupt INT_MTU2_MTU0_TGIC0
extern void INT_MTU2_MTU0_TGIC0(void);

// 159 MTU2 MTU0 TGID0
#pragma interrupt INT_MTU2_MTU0_TGID0
extern void INT_MTU2_MTU0_TGID0(void);

// 160 MTU2 MTU0 TCIV0
#pragma interrupt INT_MTU2_MTU0_TCIV0
extern void INT_MTU2_MTU0_TCIV0(void);

// 161 MTU2 MTU0 TGIE0
#pragma interrupt INT_MTU2_MTU0_TGIE0
extern void INT_MTU2_MTU0_TGIE0(void);

// 162 MTU2 MTU0 TGIF0
#pragma interrupt INT_MTU2_MTU0_TGIF0
extern void INT_MTU2_MTU0_TGIF0(void);

// 163 Reserved

// 164 MTU2 MTU1 TGIA1
#pragma interrupt INT_MTU2_MTU1_TGIA1
extern void INT_MTU2_MTU1_TGIA1(void);

// 165 MTU2 MTU1 TGIB1
#pragma interrupt INT_MTU2_MTU1_TGIB1
extern void INT_MTU2_MTU1_TGIB1(void);

// 166 Reserved 

// 167 Reserved

// 168 MTU2 MTU1 TCIV1
#pragma interrupt INT_MTU2_MTU1_TCIV1
extern void INT_MTU2_MTU1_TCIV1(void);

// 169 MTU2 MTU1 TCIU1
#pragma interrupt INT_MTU2_MTU1_TCIU1
extern void INT_MTU2_MTU1_TCIU1(void);

// 170 Reserved 

// 171 Reserved

// 172 MTU2 MTU2 TGIA2
#pragma interrupt INT_MTU2_MTU2_TGIA2
extern void INT_MTU2_MTU2_TGIA2(void);

// 173 MTU2 MTU2 TGIB2
#pragma interrupt INT_MTU2_MTU2_TGIB2
extern void INT_MTU2_MTU2_TGIB2(void);

// 174 Reserved 

// 175 Reserved

// 176 MTU2 MTU2 TCIV2
#pragma interrupt INT_MTU2_MTU2_TCIV2
extern void INT_MTU2_MTU2_TCIV2(void);

// 177 MTU2 MTU2 TCIU2
#pragma interrupt INT_MTU2_MTU2_TCIU2
extern void INT_MTU2_MTU2_TCIU2(void);

// 178 Reserved 

// 179 Reserved

// 180 MTU2 MTU3 TGIA3
#pragma interrupt INT_MTU2_MTU3_TGIA3
extern void INT_MTU2_MTU3_TGIA3(void);

// 181 MTU2 MTU3 TGIB3
#pragma interrupt INT_MTU2_MTU3_TGIB3
extern void INT_MTU2_MTU3_TGIB3(void);

// 182 MTU2 MTU3 TGIC3
#pragma interrupt INT_MTU2_MTU3_TGIC3
extern void INT_MTU2_MTU3_TGIC3(void);

// 183 MTU2 MTU3 TGID3
#pragma interrupt INT_MTU2_MTU3_TGID3
extern void INT_MTU2_MTU3_TGID3(void);

// 184 MTU2 MTU3 TCIV3
#pragma interrupt INT_MTU2_MTU3_TCIV3
extern void INT_MTU2_MTU3_TCIV3(void);

// 185 Reserved 

// 186 Reserved

// 187 Reserved 

// 188 MTU2 MTU4 TGIA4
#pragma interrupt INT_MTU2_MTU4_TGIA4
extern void INT_MTU2_MTU4_TGIA4(void);

// 189 MTU2 MTU4 TGIB4
#pragma interrupt INT_MTU2_MTU4_TGIB4
extern void INT_MTU2_MTU4_TGIB4(void);

// 190 MTU2 MTU4 TGIC4
#pragma interrupt INT_MTU2_MTU4_TGIC4
extern void INT_MTU2_MTU4_TGIC4(void);

// 191 MTU2 MTU4 TGID4
#pragma interrupt INT_MTU2_MTU4_TGID4
extern void INT_MTU2_MTU4_TGID4(void);

// 192 MTU2 MTU4 TCIV4
#pragma interrupt INT_MTU2_MTU4_TCIV4
extern void INT_MTU2_MTU4_TCIV4(void);

// 193 Reserved 

// 194 Reserved

// 195 Reserved 

// 196 MTU2 MTU5 TGIU5
#pragma interrupt INT_MTU2_MTU5_TGIU5
extern void INT_MTU2_MTU5_TGIU5(void);

// 197 MTU2 MTU5 TGIV5
#pragma interrupt INT_MTU2_MTU5_TGIV5
extern void INT_MTU2_MTU5_TGIV5(void);

// 198 MTU2 MTU5 TGIW5
#pragma interrupt INT_MTU2_MTU5_TGIW5
extern void INT_MTU2_MTU5_TGIW5(void);

// 199 Reserved 

// 200 POE2 OEI1
#pragma interrupt INT_POE2_OEI1
extern void INT_POE2_OEI1(void);

// 201 POE2 OEI2 
#pragma interrupt INT_POE2_OEI2
extern void INT_POE2_OEI2(void);

// 202 Reserved 

// 203 Reserved

// 204 MTU2S MTU3S TGIA3
#pragma interrupt INT_MTU2S_MTU3S_TGIA3
extern void INT_MTU2S_MTU3S_TGIA3(void);

// 205 MTU2S MTU3S TGIB3
#pragma interrupt INT_MTU2S_MTU3S_TGIB3
extern void INT_MTU2S_MTU3S_TGIB3(void);

// 206 MTU2S MTU3S TGIC3
#pragma interrupt INT_MTU2S_MTU3S_TGIC3
extern void INT_MTU2S_MTU3S_TGIC3(void);

// 207 MTU2S MTU3S TGID3 
#pragma interrupt INT_MTU2S_MTU3S_TGID3
extern void INT_MTU2S_MTU3S_TGID3(void);

// 208 MTU2S MTU3S TCIV3
#pragma interrupt INT_MTU2S_MTU3S_TCIV3
extern void INT_MTU2S_MTU3S_TCIV3(void);

// 209 Reserved 

// 210 Reserved 

// 211 Reserved

// 212 MTU2S MTU4S TGIA4
#pragma interrupt INT_MTU2S_MTU4S_TGIA4
extern void INT_MTU2S_MTU4S_TGIA4(void);

// 213 MTU2S MTU4S TGIB4
#pragma interrupt INT_MTU2S_MTU4S_TGIB4
extern void INT_MTU2S_MTU4S_TGIB4(void);

// 214 MTU2S MTU4S TGIC4
#pragma interrupt INT_MTU2S_MTU4S_TGIC4
extern void INT_MTU2S_MTU4S_TGIC4(void);

// 215 MTU2S MTU4S TGID4
#pragma interrupt INT_MTU2S_MTU4S_TGID4
extern void INT_MTU2S_MTU4S_TGID4(void);

// 216 MTU2S MTU4S TCIV4
#pragma interrupt INT_MTU2S_MTU4S_TCIV4
extern void INT_MTU2S_MTU4S_TCIV4(void);

// 217 Reserved 

// 218 Reserved

// 219 Reserved 

// 220 MTU2S MTU5S TGIU5
#pragma interrupt INT_MTU2S_MTU5S_TGIU5
extern void INT_MTU2S_MTU5S_TGIU5(void);

// 221 MTU2S MTU5S TGIV5
#pragma interrupt INT_MTU2S_MTU5S_TGIV5
extern void INT_MTU2S_MTU5S_TGIV5(void);

// 222 MTU2S MTU5S TGIW5
#pragma interrupt INT_MTU2S_MTU5S_TGIW5
extern void INT_MTU2S_MTU5S_TGIW5(void);

// 223 Reserved

// 224 POE2 OEI3
#pragma interrupt INT_POE2_OEI3
extern void INT_POE2_OEI3(void);

// 225 Reserved

// 226 USB USI0
#pragma interrupt INT_USB_USI0
extern void INT_USB_USI0(void);

// 227 USB USI1
#pragma interrupt INT_USB_USI1
extern void INT_USB_USI1(void);

// 228 IIC3 STPI
#pragma interrupt INT_IIC3_STPI
extern void INT_IIC3_STPI(void);

// 229 IIC3 NAKI
#pragma interrupt INT_IIC3_NAKI
extern void INT_IIC3_NAKI(void);

// 230 IIC3 RXI
#pragma interrupt INT_IIC3_RXI
extern void INT_IIC3_RXI(void);

// 231 IIC3 TXI
#pragma interrupt INT_IIC3_TXI
extern void INT_IIC3_TXI(void);

// 232 IIC3 TEI
#pragma interrupt INT_IIC3_TEI
extern void INT_IIC3_TEI(void);

// 233 SSU SSERI
#pragma interrupt INT_SSU_SSERI
extern void INT_SSU_SSERI(void);

// 234 SSU SSRXI
#pragma interrupt INT_SSU_SSRXI
extern void INT_SSU_SSRXI(void);

// 235 SSU SSTXI
#pragma interrupt INT_SSU_SSTXI
extern void INT_SSU_SSTXI(void);

// 236 SCI SCI4 ERI4
#pragma interrupt INT_SCI_SCI4_ERI4
extern void INT_SCI_SCI4_ERI4(void);

// 237 SCI SCI4 RXI4
#pragma interrupt INT_SCI_SCI4_RXI4
extern void INT_SCI_SCI4_RXI4(void);

// 238 SCI SCI4 TXI4
#pragma interrupt INT_SCI_SCI4_TXI4
extern void INT_SCI_SCI4_TXI4(void);

// 239 SCI SCI4 TEI4
#pragma interrupt INT_SCI_SCI4_TEI4
extern void INT_SCI_SCI4_TEI4(void);

// 240 SCI SCI0 ERI0
#pragma interrupt INT_SCI_SCI0_ERI0
extern void INT_SCI_SCI0_ERI0(void);

// 241 SCI SCI0 RXI0
#pragma interrupt INT_SCI_SCI0_RXI0
extern void INT_SCI_SCI0_RXI0(void);

// 242 SCI SCI0 TXI0
#pragma interrupt INT_SCI_SCI0_TXI0
extern void INT_SCI_SCI0_TXI0(void);

// 243 SCI SCI0 TEI0
#pragma interrupt INT_SCI_SCI0_TEI0
extern void INT_SCI_SCI0_TEI0(void);

// 244 SCI SCI1 ERI1
#pragma interrupt INT_SCI_SCI1_ERI1
extern void INT_SCI_SCI1_ERI1(void);

// 245 SCI SCI1 RXI1
#pragma interrupt INT_SCI_SCI1_RXI1
extern void INT_SCI_SCI1_RXI1(void);

// 246 SCI SCI1 TXI1
#pragma interrupt INT_SCI_SCI1_TXI1
extern void INT_SCI_SCI1_TXI1(void);

// 247 SCI SCI1 TEI1
#pragma interrupt INT_SCI_SCI1_TEI1
extern void INT_SCI_SCI1_TEI1(void);

// 248 SCI SCI2 ERI2
#pragma interrupt INT_SCI_SCI2_ERI2
extern void INT_SCI_SCI2_ERI2(void);

// 249 SCI SCI2 RXI2
#pragma interrupt INT_SCI_SCI2_RXI2
extern void INT_SCI_SCI2_RXI2(void);

// 250 SCI SCI2 TXI2
#pragma interrupt INT_SCI_SCI2_TXI2
extern void INT_SCI_SCI2_TXI2(void);

// 251 SCI SCI2 TEI2
#pragma interrupt INT_SCI_SCI2_TEI2
extern void INT_SCI_SCI2_TEI2(void);

// 252 SCIF SCIF3 BRI3
#pragma interrupt INT_SCIF_SCIF3_BRI3
extern void INT_SCIF_SCIF3_BRI3(void);

// 253 SCIF SCIF3 ERI3
#pragma interrupt INT_SCIF_SCIF3_ERI3
extern void INT_SCIF_SCIF3_ERI3(void);

// 254 SCIF SCIF3 RXI3
#pragma interrupt INT_SCIF_SCIF3_RXI3
extern void INT_SCIF_SCIF3_RXI3(void);

// 255 SCIF SCIF3 TXI3
#pragma interrupt INT_SCIF_SCIF3_TXI3
extern void INT_SCIF_SCIF3_TXI3(void);

// 256 Reserved

// 257 Reserved

// 258 Reserved

// 259 Reserved

// 260 Reserved

// 261 Reserved

// 262 Reserved

// 263 Reserved

// 264 Reserved

// 265 Reserved

// 266 Reserved

// 267 Reserved

// 268 Reserved

// 269 Reserved

// 270 Reserved

// 271 Reserved

// 272 Reserved

// 273 Reserved

// 274 Reserved

// 275 Reserved

// 276 Reserved

// 277 Reserved

// 278 Reserved

// 279 Reserved

// 280 Reserved

// 281 Reserved

// 282 Reserved

// 283 Reserved

// 284 Reserved

// 285 Reserved

// 286 Reserved

// 287 Reserved

// 288 Reserved

// 289 Reserved

// 290 Reserved

// 291 Reserved

// 292 Reserved

// 293 Reserved

// 294 Reserved

// 295 Reserved

// 296 Reserved

// 297 Reserved

// 298 Reserved

// 299 Reserved

// 300 Reserved

// 301 Reserved

// 302 Reserved

// 303 Reserved

// 304 Reserved

// 305 Reserved

// 306 Reserved

// 307 Reserved

// 308 Reserved

// 309 Reserved

// 310 Reserved

// 311 Reserved

// 312 Reserved

// 313 Reserved

// 314 Reserved

// 315 Reserved

// 316 Reserved

// 317 Reserved

// 318 Reserved

// 319 Reserved

// 320 Reserved

// 321 Reserved

// 322 Reserved

// 323 Reserved

// 324 Reserved

// 325 Reserved

// 326 Reserved

// 327 Reserved

// 328 Reserved

// 329 Reserved

// 330 Reserved

// 331 Reserved

// 332 Reserved

// 333 Reserved

// 334 Reserved

// 335 Reserved

// 336 Reserved

// 337 Reserved

// 338 Reserved

// 339 Reserved

// 340 Reserved

// 341 Reserved

// 342 Reserved

// 343 Reserved

// 344 Reserved

// 345 Reserved

// 346 Reserved

// 347 Reserved

// 348 Reserved

// 349 Reserved

// 350 Reserved

// 351 Reserved

// 352 Reserved

// 353 Reserved

// 354 Reserved

// 355 Reserved

// 356 Reserved

// 357 Reserved

// 358 Reserved

// 359 Reserved

// 360 Reserved

// 361 Reserved

// 362 Reserved

// 363 Reserved

// 364 Reserved

// 365 Reserved

// 366 Reserved

// 367 Reserved

// 368 Reserved

// 369 Reserved

// 370 Reserved

// 371 Reserved

// 372 Reserved

// 373 Reserved

// 374 Reserved

// 375 Reserved

// 376 Reserved

// 377 Reserved

// 378 Reserved

// 379 Reserved

// 380 Reserved

// 381 Reserved

// 382 Reserved

// 383 Reserved

// 384 Reserved

// 385 Reserved

// 386 Reserved

// 387 Reserved

// 388 Reserved

// 389 Reserved

// 390 Reserved

// 391 Reserved

// 392 Reserved

// 393 Reserved

// 394 Reserved

// 395 Reserved

// 396 Reserved

// 397 Reserved

// 398 Reserved

// 399 Reserved

// 400 Reserved

// 401 Reserved

// 402 Reserved

// 403 Reserved

// 404 Reserved

// 405 Reserved

// 406 Reserved

// 407 Reserved

// 408 Reserved

// 409 Reserved

// 410 Reserved

// 411 Reserved

// 412 Reserved

// 413 Reserved

// 414 Reserved

// 415 Reserved

// 416 Reserved

// 417 Reserved

// 418 Reserved

// 419 Reserved

// 420 Reserved

// 421 Reserved

// 422 Reserved

// 423 Reserved

// 424 Reserved

// 425 Reserved

// 426 Reserved

// 427 Reserved

// 428 Reserved

// 429 Reserved

// 430 Reserved

// 431 Reserved

// 432 Reserved

// 433 Reserved

// 434 Reserved

// 435 Reserved

// 436 Reserved

// 437 Reserved

// 438 Reserved

// 439 Reserved

// 440 Reserved

// 441 Reserved

// 442 Reserved

// 443 Reserved

// 444 Reserved

// 445 Reserved

// 446 Reserved

// 447 Reserved

// 448 Reserved

// 449 Reserved

// 450 Reserved

// 451 Reserved

// 452 Reserved

// 453 Reserved

// 454 Reserved

// 455 Reserved

// 456 Reserved

// 457 Reserved

// 458 Reserved

// 459 Reserved

// 460 Reserved

// 461 Reserved

// 462 Reserved

// 463 Reserved

// 464 Reserved

// 465 Reserved

// 466 Reserved

// 467 Reserved

// 468 Reserved

// 469 Reserved

// 470 Reserved

// 471 Reserved

// 472 Reserved

// 473 Reserved

// 474 Reserved

// 475 Reserved

// 476 Reserved

// 477 Reserved

// 478 Reserved

// 479 Reserved

// 480 Reserved

// 481 Reserved

// 482 Reserved

// 483 Reserved

// 484 Reserved

// 485 Reserved

// 486 Reserved

// 487 Reserved

// 488 Reserved

// 489 Reserved

// 490 Reserved

// 491 Reserved

// 492 Reserved

// 493 Reserved

// 494 Reserved

// 495 Reserved

// 496 Reserved

// 497 Reserved

// 498 Reserved

// 499 Reserved

// 500 Reserved

// 501 Reserved

// 502 Reserved

// 503 Reserved

// 504 Reserved

// 505 Reserved

// 506 Reserved

// 507 Reserved

// 508 Reserved

// 509 Reserved

// 510 Reserved

// 511 Reserved

// Reserved
#pragma interrupt Dummy
extern void Dummy(void);
